# Generated by Django 5.1.2 on 2024-10-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
    ]
